#lang scribble/lp2

@(require "tamer.rkt")

@(require (for-syntax "tamer.rkt"))

@handbook-story{Search Engine Optimization}

As a beginning practitioner of @deftech{@hyperlink["http://en.wikipedia.org/wiki/Search_engine_optimization"]{SEO}},
I follows Google@literal{'}s guides.

Meanwhile, @hyperlink["http://en.wikipedia.org/wiki/Webserver_directory_index"]{directory indices}
are @litchar{default.rkt} and @litchar{index.html}, respectively.

@tamer-smart-summary[]

@chunk[|<seo taming start>|
       (require "tamer.rkt")
       (tamer-taming-start)
       (define-values {shutdown curl 127.curl} (sakuyamon-realize))
       |<seo:*>|]

@handbook-scenario{Robots Exclusion Protocol}

@tamer-note['robots.txt]

@handbook-rule{Every @itech{Terminus} should have a @litchar{robots.txt} file placed in the proper directory.}

@chunk[|<testcase: robots.txt>|
       (for ([/webroot (in-list (list /htdocs /tamer /digimon))])
         (test-case (format "200|503: ~a" (/webroot "robots.txt"))
                    (match-let ([{list status reason _ _} (curl (/webroot "robots.txt"))])
                      (check-pred (curryr member '{200 503}) status reason))))]

@handbook-scenario{Server Side Redirection}

@tamer-note['redirections]

@handbook-rule{All non-/-suffixed directories should be redirected to their /-suffixed counterparts.}

@chunk[|<testcase: dir to dir/>|
       (for ([rpath (in-list (list "." "~:" "stone"))])
         (test-case (format "302: ~a" rpath)
                    (match-let ([{list status reason headers _} (curl (/htdocs rpath))])
                      (check-eq? status 302 reason)
                      (check-regexp-match #px"/$" (dict-ref headers 'location)))))]

@handbook-rule{Paths reference to any @litchar{*.rkt} should be redirected to their @litchar{*.html} counterparts.}

@itech{Terminus} like @itech{Per-Digimon Terminus} serves static contents that usually be auto-generated by @bold{Scribble}.
The rendered @litchar{*.html}s will be placed within directories that up to 2 depths, thereforce the path parts of
@litchar{*.rkt} if exist should be fixed either.

@chunk[|<testcase: rkt to html>|
       (for ([rpath (in-list (list "seo.rkt" "dir/dot.lp.rkt"))])
         (test-case (format "302: ~a" rpath)
                    (match-let ([{list status reason headers _} (curl (/digimon rpath))])
                      (check-eq? status 302 reason)
                      (check-regexp-match #px"/[^/.]+?(/|\\.html)$" (dict-ref headers 'location)))))]

@handbook-appendix{SEO Auxiliaries}

@chunk[|<seo:*>|
       {module+ main (call-as-normal-termination tamer-prove)}
       {module+ story
         (define-tamer-suite robots.txt "/robots.txt"
           |<seo: check #:before>|
           |<testcase: robots.txt>|)
         
         (define-tamer-suite redirections "Server Side Redirections"
           |<seo: check #:before>| #:after {λ _ (shutdown)}
           (test-suite "dir -> dir/" |<testcase: dir to dir/>|)
           (test-suite "rkt -> html" |<testcase: rkt to html>|))}]

@chunk[|<seo: check #:before>|
       #:before {λ _ (when (string? 127.curl) (raise-result-error 'realize "procedure?" 127.curl))}]
